spring:
  application:
    name: quotes

  data:
    mongodb:
      host: localhost
      port: 27017
      database: challenge
      # required since we have search by author functionality
      auto-index-creation: true